dataset:
  Training_dataset: ../../OT-TCR/data/Inter/donor_all/donor_all.h5ad
  Training_profile_dist: ../../OT-TCR/data/Inter/donor_all/donor_all_RNA_dist.h5ad
  Training_tcr_dist: ../../OT-TCR/data/Inter/donor_all/donor_all_TRB_dist.h5ad
Train:
  Sampling:
    batch_size: 256
    sample_shuffle: True
  
  Model_Parameter:
    encoderTCR_in_dim: 5
    encoderTCR_out_dim: 256
    encoderprofile_in_dim: 5000
    encoderprofile_hid_dim: 1024
    encoderprofile_hid_dim2: 512
    encoderprofle_out_dim: 256
    out_dim: 256
    head_num: 4
    device: cuda

  Trainer_parameter:
    random_seed: 888
    epoch: 150
    # epoch: 10
    learning_rate: 0.0001
  
  output_dir: ../TCR_result/Inter

Inference:
  Sampling:
    batch_size: 256
    sample_shuffle: False
  Model: /Model_checkpoints/epoch150_model.pth